# Generated by Django 3.1.4 on 2021-10-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20211002_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='Идентификатор пользователя')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
            ],
        ),
    ]
