# Generated by Django 3.1.4 on 2021-10-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.answer'),
        ),
    ]
